package com.feiyou.headstyle.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "MY_CREATE_INFO".
 */
@Entity
public class MyCreateInfo {

    @Id
    private Long id;

    @NotNull
    private String uid;

    @NotNull
    private String photo_id;

    @Generated(hash = 917159373)
    public MyCreateInfo() {
    }

    public MyCreateInfo(Long id) {
        this.id = id;
    }

    @Generated(hash = 1917302786)
    public MyCreateInfo(Long id, @NotNull String uid, @NotNull String photo_id) {
        this.id = id;
        this.uid = uid;
        this.photo_id = photo_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUid() {
        return uid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUid(@NotNull String uid) {
        this.uid = uid;
    }

    @NotNull
    public String getPhoto_id() {
        return photo_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoto_id(@NotNull String photo_id) {
        this.photo_id = photo_id;
    }

}
