package com.feiyou.headstyle.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.feiyou.headstyle.db.MyCreateInfo;

import com.feiyou.headstyle.db.greendao.MyCreateInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myCreateInfoDaoConfig;

    private final MyCreateInfoDao myCreateInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myCreateInfoDaoConfig = daoConfigMap.get(MyCreateInfoDao.class).clone();
        myCreateInfoDaoConfig.initIdentityScope(type);

        myCreateInfoDao = new MyCreateInfoDao(myCreateInfoDaoConfig, this);

        registerDao(MyCreateInfo.class, myCreateInfoDao);
    }
    
    public void clear() {
        myCreateInfoDaoConfig.clearIdentityScope();
    }

    public MyCreateInfoDao getMyCreateInfoDao() {
        return myCreateInfoDao;
    }

}
