package com.feiyou.headstyle.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.feiyou.headstyle.bean.BannerInfo;
import com.feiyou.headstyle.bean.HeadInfo;
import com.feiyou.headstyle.bean.MyCreateInfo;
import com.feiyou.headstyle.bean.SpecialInfo;

import com.feiyou.headstyle.db.greendao.BannerInfoDao;
import com.feiyou.headstyle.db.greendao.HeadInfoDao;
import com.feiyou.headstyle.db.greendao.MyCreateInfoDao;
import com.feiyou.headstyle.db.greendao.SpecialInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bannerInfoDaoConfig;
    private final DaoConfig headInfoDaoConfig;
    private final DaoConfig myCreateInfoDaoConfig;
    private final DaoConfig specialInfoDaoConfig;

    private final BannerInfoDao bannerInfoDao;
    private final HeadInfoDao headInfoDao;
    private final MyCreateInfoDao myCreateInfoDao;
    private final SpecialInfoDao specialInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bannerInfoDaoConfig = daoConfigMap.get(BannerInfoDao.class).clone();
        bannerInfoDaoConfig.initIdentityScope(type);

        headInfoDaoConfig = daoConfigMap.get(HeadInfoDao.class).clone();
        headInfoDaoConfig.initIdentityScope(type);

        myCreateInfoDaoConfig = daoConfigMap.get(MyCreateInfoDao.class).clone();
        myCreateInfoDaoConfig.initIdentityScope(type);

        specialInfoDaoConfig = daoConfigMap.get(SpecialInfoDao.class).clone();
        specialInfoDaoConfig.initIdentityScope(type);

        bannerInfoDao = new BannerInfoDao(bannerInfoDaoConfig, this);
        headInfoDao = new HeadInfoDao(headInfoDaoConfig, this);
        myCreateInfoDao = new MyCreateInfoDao(myCreateInfoDaoConfig, this);
        specialInfoDao = new SpecialInfoDao(specialInfoDaoConfig, this);

        registerDao(BannerInfo.class, bannerInfoDao);
        registerDao(HeadInfo.class, headInfoDao);
        registerDao(MyCreateInfo.class, myCreateInfoDao);
        registerDao(SpecialInfo.class, specialInfoDao);
    }
    
    public void clear() {
        bannerInfoDaoConfig.clearIdentityScope();
        headInfoDaoConfig.clearIdentityScope();
        myCreateInfoDaoConfig.clearIdentityScope();
        specialInfoDaoConfig.clearIdentityScope();
    }

    public BannerInfoDao getBannerInfoDao() {
        return bannerInfoDao;
    }

    public HeadInfoDao getHeadInfoDao() {
        return headInfoDao;
    }

    public MyCreateInfoDao getMyCreateInfoDao() {
        return myCreateInfoDao;
    }

    public SpecialInfoDao getSpecialInfoDao() {
        return specialInfoDao;
    }

}
